trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: Build Increment Version
  inputs:
    targetType: 'inline'
    script: 'cargo build --release'

- task: Bash@3
  displayName: Copy Bin and Check Files
  inputs:
    targetType: 'inline'
    script: |
      cp target/release/increment_version ./increment_version

- task: Bash@3
  displayName: Run Tests
  inputs:
    targetType: 'inline'
    workingDirectory: $(System.DefaultWorkingDirectory)/tests
    script: |
      ./run_tests.sh